export const ST = {
  root: { display: 'flex', flexDirection: 'column' as const, gap: '20px', padding: '4px 0', maxWidth: '640px' },
  headerRow: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap' as const },
  h2: { color: 'var(--dsw-alias-label-primary)', fontSize: '18px', fontWeight: 600, margin: 0 },
  sub: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '13px' },
  hr: { height: '1px', background: 'var(--dsw-alias-border-l2)', border: 'none', margin: '4px 0' },
  label: { color: 'var(--dsw-alias-label-primary)', fontSize: '16px', fontWeight: 600, marginBottom: '8px' },
  hint: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '12px', lineHeight: '18px', marginTop: '4px' },
  colorHint: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '12px', lineHeight: '18px', marginTop: '7px', textAlign: 'center' as const },
  wheelCanvas: { cursor: 'crosshair', borderRadius: '50%' },
  center: { display: 'flex', justifyContent: 'center' },
  // Wheel on the left, precise HSL/RGB entry on the right.
  wheelRow: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '24px', flexWrap: 'wrap' as const },
  inputPanel: { display: 'flex', flexDirection: 'column' as const, gap: '10px', minWidth: '168px' },
  inputTabs: { display: 'flex', gap: '6px' },
  inputTab: { height: '26px', padding: '0 12px', borderRadius: '6px', border: '1px solid var(--dsw-alias-border-l2)', background: 'var(--dsw-alias-button-elevated-fill)', color: 'var(--dsw-alias-label-tertiary)', cursor: 'pointer', fontSize: '12px', font: 'inherit' },
  inputTabActive: { background: 'var(--dsw-alias-brand-primary)', color: 'var(--dsw-alias-brand-text)', borderColor: 'transparent' },
  inputGrid: { display: 'flex', flexDirection: 'column' as const, gap: '6px' },
  inputField: { display: 'flex', alignItems: 'center', gap: '8px' },
  inputLabel: { color: 'var(--dsw-alias-label-secondary)', fontSize: '12px', width: '14px', textAlign: 'center' as const },
  input: { flex: 1, height: '28px', padding: '0 8px', borderRadius: '6px', border: '1px solid var(--dsw-alias-border-l2)', background: 'var(--dsw-alias-button-elevated-fill)', color: 'var(--dsw-alias-label-primary)', fontSize: '12px', font: 'inherit', boxSizing: 'border-box' as const, minWidth: '0' },
  swatch: { height: '22px', borderRadius: '6px', border: '1px solid var(--dsw-alias-border-l2)' },
  // Error boundary fallback
  crashBox: { display: 'flex', flexDirection: 'column' as const, gap: '10px', alignItems: 'center', padding: '24px 16px', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '10px' },
  crashTitle: { color: 'var(--dsw-alias-label-primary)', fontSize: '15px', fontWeight: 600 },
  crashDesc: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '12px', textAlign: 'center' as const },
  btnGroup: { display: 'flex', justifyContent: 'center', marginTop: '10px' },
  row: { display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' as const },
  sliderBlock: { display: 'flex', flexDirection: 'column' as const, gap: '4px' },
  sliderRow: { display: 'flex', alignItems: 'center', gap: '10px' },
  sliderLabel: { color: 'var(--dsw-alias-label-secondary)', fontSize: '13px' },
  slider: { flex: 1, accentColor: 'var(--dsw-alias-brand-primary)', minWidth: '160px' },
  sliderVal: { color: 'var(--dsw-alias-label-secondary)', fontSize: '12px', whiteSpace: 'nowrap' as const, width: '44px', textAlign: 'right' as const },
  btn: { height: '32px', padding: '0 14px', borderRadius: '8px', border: '1px solid var(--dsw-alias-border-l2)', background: 'var(--dsw-alias-button-elevated-fill)', color: 'var(--dsw-alias-label-primary)', cursor: 'pointer', fontSize: '13px', font: 'inherit', boxSizing: 'border-box' as const },
  btnDanger: { color: 'var(--dsw-alias-state-error-primary)' },
  btnPrimary: { background: 'var(--dsw-alias-brand-primary)', color: 'var(--dsw-alias-brand-text)', border: 'none' },
  preview: { width: '368px', height: '225px', objectFit: 'cover' as const, borderRadius: '6px', border: '1px solid var(--dsw-alias-border-l2)', cursor: 'pointer' },
  sliders: { display: 'flex', flexDirection: 'column' as const, gap: '12px', marginTop: '8px' },
  // Modal
  overlay: { position: 'fixed' as const, inset: 0, zIndex: 9999, background: 'rgba(0,0,0,0.7)', display: 'flex', flexDirection: 'column' as const, alignItems: 'center', justifyContent: 'center', gap: '12px' },
  modalTitle: { color: '#fff', fontSize: '16px', fontWeight: 500 },
  modalHint: { color: 'rgba(255,255,255,0.6)', fontSize: '12px' },
  previewRect: { position: 'relative' as const, overflow: 'hidden', border: '2px solid rgba(255,255,255,0.3)', borderRadius: '8px', background: '#000', cursor: 'grab' },
  previewImg: { position: 'absolute' as const, transformOrigin: '0 0', pointerEvents: 'none' as const },
  modalBtns: { display: 'flex', gap: '10px' },
  // Eyedropper modal
  pickerBox: { maxWidth: 'min(90vw, 720px)', maxHeight: '60vh', overflow: 'hidden', borderRadius: '8px', border: '2px solid rgba(255,255,255,0.3)', background: '#000', cursor: 'crosshair' },
  pickerCanvas: { display: 'block', maxWidth: '100%', maxHeight: '60vh', objectFit: 'contain' as const },
  pickerBar: { display: 'flex', alignItems: 'center', gap: '10px', minWidth: '260px' },
  pickerSwatch: { width: '28px', height: '28px', borderRadius: '6px', border: '1px solid rgba(255,255,255,0.4)', flexShrink: 0 },
  pickerValue: { color: '#fff', fontSize: '13px', fontFamily: 'monospace' },
  magnifier: { position: 'fixed' as const, width: '96px', height: '96px', borderRadius: '50%', border: '2px solid rgba(255,255,255,0.7)', boxShadow: '0 4px 16px rgba(0,0,0,0.5)', zIndex: 10000, background: '#000', pointerEvents: 'none' as const, transition: 'opacity 0.08s' },
}
